<?php

namespace Volvo\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionTypeRepository extends EntityRepository
{
}
