<?php

namespace Volvo\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VolvoUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolvoUserRepository extends EntityRepository
{
}
