parameters:
#    volvo_security.example.class: Volvo\SecurityBundle\Example

services:
#    volvo_security.example:
#        class: %volvo_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
