parameters:
#    volvo_admin.example.class: Volvo\AdminBundle\Example

services:
#    volvo_admin.example:
#        class: %volvo_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
